FROM node:15.11.0-alpine3.10

WORKDIR 'app/'

COPY ["src/", "./src/"]

COPY ["package.json", "package-lock.json", "./"]

COPY [".eslintrc.json", ".prettierrc", "./"]

ENV LOCAL_ENABLED=true

RUN npm ci --also=dev

# You can overwrite command in `serverless.yml` template
CMD ["npm", "run", "ci:test"]
