const sourceOptions = {
  // Required
  id: "id",
  name: "name",
  author: "author",
  genre: "genre",
  description: "description",
  synopsis: "synopsis",
  categories: "categories",
  slug: "slug",
  hpbUsedPrice: "hpbUsedPrice",
  hpbNewPrice: "hpbNewPrice",
  hasNativeImage: "hasNativeImage",
  rareFind: "rareFind",
  firstEdition: "firstEdition",
  signed: "signed",
  upc: "upc",
  publicationDate: "publicationDate",
  subtitle: "subtitle",

  // Extras
  nytRankings: "nytRankings",
  type: "type",
  by: "by",
  salesRankHpbStore: "salesRankHpbStore",
  salesBlurb: "salesBlurb",
  formatDescription: "formatDescription",
  genreParametrized: "genreParametrized",
  staffPick: "staffPick",
  director: "director",
  artist: "artist",
  createdAt: "createdAt",
  indexedAt: "indexedAt",
  updatedAt: "updatedAt",
};

module.exports = {
  sourceOptions: sourceOptions,
  standardOptions: [
    sourceOptions.id,
    sourceOptions.name,
    sourceOptions.author,
    sourceOptions.genre,
    sourceOptions.description,
    sourceOptions.categories,
    sourceOptions.slug,
    sourceOptions.hpbNewPrice,
    sourceOptions.hpbUsedPrice,
    sourceOptions.rareFind,
    sourceOptions.firstEdition,
    sourceOptions.signed,
    sourceOptions.publicationDate,
    sourceOptions.subtitle,
    sourceOptions.synopsis,
  ],
};
