name: Main Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo Fetching project...

      - uses: actions/checkout@v2

      - run: echo Creating Docker container

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: hpbweb:latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ci
          push: false
          tags: hpbweb:latest

      - name: Run Docker image
        uses: addnab/docker-run-action@v2
        with:
          image: hpbweb:latest
