name: Main Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t hpbtest -p 3000:3000 -f Dockerfile.ci .

      - name: Run Docker image
        run: docker run hpbtest
